### ISSUE TITLE
prototxt parser error

### ISSUE THREAD

**Issue by scholltan** [marvis/pytorch-caffe#5]
pytorch_blobs, pytorch_models = forward_pytorch(protofile, weightfile, image)
  File "tsq-test.py", line 23, in forward_pytorch
    net = CaffeNet(protofile)
  File "/root/tsq/pytorch-caffe/caffenet.py", line 380, in __init__
    self.net_info = parse_prototxt(protofile)
  File "/root/tsq/pytorch-caffe/prototxt.py", line 79, in parse_prototxt
    layer = parse_block(fp)
  File "/root/tsq/pytorch-caffe/prototxt.py", line 34, in parse_block
    key, value = line.split(':')
ValueError: too many values to unpack

**Comment by HaoWangXiDian** [comment]
just make sure one ':' in one line

**Comment by samedsaka** [comment]
> just make sure one ':' in one line

@scholltan is this solve your error?

**Comment by Ellinier** [comment]
Hello, I just meet the same problem. Could any one tell me how to solve it?

**Comment by RichardoTiono** [comment]
> Hello, I just meet the same problem. Could any one tell me how to solve it?
> 
> I have solved it.

Hi can you share how to resolve this? I have encountered same problem and the value looks like this `
['name', ' "data"']
['type', ' "Input"']
['top', ' "data"']
['input_param { shape', ' { dim', ' 1 dim', ' 3 dim', ' 128 dim', ' 128} }']
`

**Comment by Ellinier** [comment]
> name: "data"
> type: "Input"
> top: "data"
> input_param { shape: { dim: 1 dim: 3 dim: 128 dim: 128} }

just change the layout like this：
name: "data"
type: "Input"
top: "data"
input_param { 
	shape: { 
		dim: 1 
		dim: 3 
		dim: 128 
		dim: 128
	} 
}

**Comment by RichardoTiono** [comment]
> > name: "data"
> > type: "Input"
> > top: "data"
> > input_param { shape: { dim: 1 dim: 3 dim: 128 dim: 128} }
> 
> just change the layout like this：
> 
> > name: "data"
> > type: "Input"
> > top: "data"
> > input_param {
> > shape: {
> > dim: 1
> > dim: 3
> > dim: 128
> > dim: 128
> > }
> > }

Hi, it seems your solution works if you don't mind tho, does your caffe model also use input_param like that? Because when I check the caffenet.py it doesn't has layer['input_param']

**Comment by Ellinier** [comment]
Hello, my caffe model doesn't use input_param like this. But it defines the shape of input data in the prototxt file in the following format: 
> input: "data"
> input_dim: 1
> input_dim: 3
> input_dim: 128
> input_dim: 128
Maybe you can change it and have a try.
